spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test-exposed
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8081
logging:
  level:
    Exposed: DEBUG